### PR TITLE
Rename canonical names using SMPTE ST 2065-4 as a model

### LINKED ISSUE #63: Match attributes with SMPTE 2065-4 - ACES Image Container File
Attribute names here are a "_" format, rather than the camelCase format that is used for existing SMPTE 2065-4 spec.

Here is a spreadsheet that matches the SMPTE attributes against, the OSVP VFX parameters:

https://docs.google.com/spreadsheets/d/1z75TXNsh437NIOQXQJ2e0gfv5cmu3_E_/edit#gid=1127003645

 I'm happy to make a patch request for this, if this makes sense.

### PR DESCRIPTION
**Pull request by richardssam**
This makes all the parameters camelCase and where appropriate makes them match the SMPTE 2065-4 parameters.

The one major exception is "aperture" which gets confusing with t-number and f-number, so we have left those as tNumber and fNumber for this iteration.

Closes #63

### CODE REVIEW

**Comment by richardssam** [comment]
This resolves issue #63

**Comment by palemieux** [comment]
@j-helman What review period do you suggest?

**Review by palemieux — CHANGES_REQUESTED** [review]
See https://github.com/sandflow/camdkit/pull/78 for required changes.

@richardssam Can you either apply the changes to your branch or accept the other branch?

**Comment by richardssam** [comment]
@palemieux I've merged in your changes.

**Pull request merged**
